title: Luna Lunapiena - Web Developer
author: Luna Lunapiena
url: "lunacodesdesign.com"
# baseurl: "jekyll_test/"
email: luna@lunacodesdesign.com
description: > # this means to ignore newlines until "show_excerpts:"
  Luna Lunapiena is a friendly and enthusiastic Web Developer, who works primarily with WordPress and Jekyll.

show_excerpts: false # set to true to show excerpts on the homepage

github_url: https://github.com/lunacodes/
twitter_url: https://mobile.twitter.com/lunacodess

# SEO - jekyll-seo-tag
# logo: "/header.png"
twitter:
  - username: lunacodess
  - card: summary
social:
  name: Luna Lunapiena
  links:
    - https://twitter.com/lunacodess
    - https://githuub.com/lunacodes
locale: en_US
# google_site_verification:

show_excerpts: false # set to true to show excerpts on the homepage
excerpt_separator: <!--more-->

kramdown:
  toc_levels: 2..3

permalink: /:categories/:year/:month/:day/:title/

collections_dir: collections
collections:
  projects:
    output: true
    permalink: /portfolio/:name/
    redirect_from: /projects/:name/
    order:
      - haSepharadi.md
      - living-poetry.md
      - us-corr.md
      - eye-to-eye.md
      - jess-dobkin.md
      - five-pillars.md
      - jay-michaels.md
      - laura-mcdonald.md
      - wandering-cellist.md
      # - arvados.md
      # - cwl.md
      # - curii.md

defaults:
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project-single"

plugins:
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-titles-from-headings

exclude:
  - _archive/
  - _scratch/

sass:
  sass_dir: _sass
  # style: compressed

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: false
